name: homelab

services:
  homepage:
    image: homelab-homepage
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: homelab
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      TZ: America/Sao_Paulo
      LINK_HOST: homelab
      DOCKER_SOCKET: /var/run/docker.sock
      HOST_ROOT: /host
      DB_PATH: /app/data/homepage.db
    volumes:
      - ../data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro,rslave
    group_add:
      - "990"
